### ISSUE TITLE
Module 12 - Accounts URL

### ISSUE THREAD

**Issue by aybarutcu** [amitjpr/mulesoft-training-solution#39]
Hi,
In the snippet file  "mulesoft download resources /APDevFundamentals4.2_studentFiles_16nov2019/APDevFundamentals4.2_snippets.txt"
, accounts URL should be "http://ilt.learn.mulesoft.com/accounts/show " instead of the link below

* MODULE 12 *********************************************************

* MUA Accounts URL
http://ilt.mulesoft-training.com/accounts/show

Regards

**Comment by amitjpr** [comment]
Thanks, You can refer Mulesoft site for the latest links. this link was put in when I went through the training.
